const TEST_BASE_URL = process.env.NEXT_PUBLIC_TEST_BASE_URL;
const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
const TEST_TOKEN = process.env.NEXT_PUBLIC_TEST_TOKEN;

export { BASE_URL, TEST_BASE_URL, TEST_TOKEN };