const GLOBAL_ERROR_CODE = {
  INVALID_INPUT_VALUE: "INVALID_INPUT_VALUE",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};

const AUTH_ERROR_CODE = {
  ALREADY_REGISTERED_EMAIL: "ALREADY_REGISTERED_EMAIL",
  ALREADY_REGISTERED_NICKNAME: "ALREADY_REGISTERED_NICKNAME",
  EXPIRED_CODE: "EXPIRED_CODE",
  INVALID_CODE: "INVALID_CODE",
  EMAIL_VALIDATION_NOT_FOUND: "EMAIL_VALIDATION_NOT_FOUND",
  ALREADY_VERIFIED_EMAIL: "ALREADY_VERIFIED_EMAIL",
};

export const ERROR_CODE = {
  ...AUTH_ERROR_CODE,
  ...GLOBAL_ERROR_CODE,
};

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
