import { initMocks } from "@/mocks";
import { MSWComponent } from "@/providers/msw-component";
import QueryProvider from "@/providers/query-provider";
import { pretendard } from "@/assets/font/fonts";
import "@/styles/globals.css";
import type { Metadata } from "next";

initMocks();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} font-pretendard`}>
        <MSWComponent>
          <QueryProvider>{children}</QueryProvider>
        </MSWComponent>
      </body>
    </html>
  );
}
